// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooManagementSystem.Data;

#nullable disable

namespace ZooManagementSystem.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    partial class ZooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Alimentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Alimentacion", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calorias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Precio")
                        .IsRequired()
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("Stock")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("StockMinimo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("ProveedorId");

                    b.ToTable("Alimento", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlimentacionId")
                        .HasColumnType("int");

                    b.Property<int?>("EcosistemaId")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("JaulaId")
                        .HasColumnType("int");

                    b.Property<string>("NombrePopular")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NombrePopular");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UrlImagen");

                    b.HasKey("Id");

                    b.HasIndex("AlimentacionId");

                    b.HasIndex("EcosistemaId");

                    b.HasIndex("JaulaId");

                    b.HasIndex("NombrePopular");

                    b.ToTable("Animal", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.CategoriaLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Sueldo")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("CategoriaLaboral", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Dosis", b =>
                {
                    b.Property<int>("DosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DosisId"));

                    b.Property<int?>("AlimentoId")
                        .HasColumnType("int");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DosisId");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Dosis", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Ecosistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion");

                    b.ToTable("Ecosistema", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apodo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CategoriasId")
                        .HasColumnType("int");

                    b.Property<string>("Cp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("JaulaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriasId");

                    b.HasIndex("JaulaId");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Jaula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ZonaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ZonaId");

                    b.ToTable("Jaula", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Zona", b =>
                {
                    b.Property<int>("ZonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZonaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EcosistemaId")
                        .HasColumnType("int");

                    b.HasKey("ZonaId");

                    b.HasIndex("EcosistemaId");

                    b.ToTable("Zona", (string)null);
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Alimento", b =>
                {
                    b.HasOne("ZooManagementSystem.Models.Entities.Proveedor", "Proveedor")
                        .WithMany("Alimentos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Alimento_Proveedor");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Animal", b =>
                {
                    b.HasOne("ZooManagementSystem.Models.Entities.Alimentacion", "Alimentacion")
                        .WithMany("Animales")
                        .HasForeignKey("AlimentacionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Animal_Alimentacion");

                    b.HasOne("ZooManagementSystem.Models.Entities.Ecosistema", "Ecosistema")
                        .WithMany("Animales")
                        .HasForeignKey("EcosistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Animal_Ecosistema");

                    b.HasOne("ZooManagementSystem.Models.Entities.Jaula", "Jaula")
                        .WithMany("Animales")
                        .HasForeignKey("JaulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Animal_Jaula");

                    b.Navigation("Alimentacion");

                    b.Navigation("Ecosistema");

                    b.Navigation("Jaula");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Dosis", b =>
                {
                    b.HasOne("ZooManagementSystem.Models.Entities.Alimento", "Alimento")
                        .WithMany("Dosis")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Dosis_Alimento");

                    b.HasOne("ZooManagementSystem.Models.Entities.Animal", "Animal")
                        .WithMany("Dosis")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Dosis_Animal");

                    b.Navigation("Alimento");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Empleado", b =>
                {
                    b.HasOne("ZooManagementSystem.Models.Entities.CategoriaLaboral", "CategoriaLaboral")
                        .WithMany("Empleados")
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Empleado_CategoriaLaboral");

                    b.HasOne("ZooManagementSystem.Models.Entities.Jaula", "Jaula")
                        .WithMany("Empleados")
                        .HasForeignKey("JaulaId")
                        .HasConstraintName("FK_Empleado_Jaula");

                    b.Navigation("CategoriaLaboral");

                    b.Navigation("Jaula");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Jaula", b =>
                {
                    b.HasOne("ZooManagementSystem.Models.Entities.Zona", "Zona")
                        .WithMany("Jaulas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Jaula_Zona");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Zona", b =>
                {
                    b.HasOne("ZooManagementSystem.Models.Entities.Ecosistema", "Ecosistema")
                        .WithMany("Zonas")
                        .HasForeignKey("EcosistemaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Zona_Ecosistema");

                    b.Navigation("Ecosistema");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Alimentacion", b =>
                {
                    b.Navigation("Animales");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Alimento", b =>
                {
                    b.Navigation("Dosis");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Animal", b =>
                {
                    b.Navigation("Dosis");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.CategoriaLaboral", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Ecosistema", b =>
                {
                    b.Navigation("Animales");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Jaula", b =>
                {
                    b.Navigation("Animales");

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Proveedor", b =>
                {
                    b.Navigation("Alimentos");
                });

            modelBuilder.Entity("ZooManagementSystem.Models.Entities.Zona", b =>
                {
                    b.Navigation("Jaulas");
                });
#pragma warning restore 612, 618
        }
    }
}
